Add Travis CI
boydm/scenic_math pull request #4
Opened 2018-09-08 09:22 UTC by harlantwood

Rebased off #2, please merge that first.

Builds are passing here: https://travis-ci.org/harlantwood/scenic_math

TODO: @boydm to activate Travis CI for this repo.

2018-09-08 09:23 UTC, harlantwood commented on Makefile
> +CFLAGS ?= -fPIC -O2 -Wall -Wextra -Wno-unused-parameter -std=c99
This is from #2

2018-09-08 09:27 UTC, yordis commented
@harlantwood make the PR against my PR so your commits make it at the same time rather than having two PRs

2018-09-08 09:32 UTC, yordis requested changes

2018-09-08 09:32 UTC, yordis commented on .travis.yml
> +  - mix test
Try to add the tools I added on `scenic` for documentation, coverage, and credo.

Also even when it is a single line in the `Makefile` rather than doing it inline in Travis it is easier to maintain and people can call the `make` command locally and see exactly what Travis is trying to do

2018-09-08 17:03 UTC, harlantwood commented
Thanks @yordis for reviewing.

> Try to add the tools I added on scenic for documentation, coverage, and credo.

I'm happy to add these but will let @boydm make the call if you want these on this repo / all Elixir repos.  

> Also even when it is a single line in the Makefile rather than doing it inline in Travis it is easier to maintain and people can call the make command locally and see exactly what Travis is trying to do

Context: this refers to the Makefile in https://github.com/boydm/scenic/pull/16

I personally disagree with this style choice.  I prefer to look at the `.travis.yml` and see what is going on directly, rather than following the trail to another file.  It also seems ugly to me to have a makefile in the root directory just for CI.  

Having said that, I'm certainly in favor of consistency across repos, whichever way we go.

@boydm any thoughts?

2018-09-08 17:52 UTC, yordis commented
@harlantwood again the only reason I put things in the makefile is that with  simple command people are running exactly what Travis runs which you would have to do manually if you have multiple steps https://github.com/boydm/scenic/blob/1193a5761d98e07c2a8844da3191ac3d3aa1a4fc/Makefile#L6-L8

I used to put everything on my Travis until I learned the lesson so I try to help the folks by these simple changes.

2018-09-08 18:37 UTC, boydm commented
Kind of a lot of pull requests right now. I'll wrap my head around this on in a bit...

2018-09-08 18:43 UTC, ijcd commented
+1 for “make ci” of some sort.

On Sat, Sep 8, 2018 at 11:37 AM Boyd Multerer <notifications@github.com>
wrote:

> Kind of a lot of pull requests right now. I'll wrap my head around this on
> in a bit...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/boydm/scenic_math/pull/4#issuecomment-419664183>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAveQGLFV3-zTAnN8pqMRN72y_FZT21ks5uZA5vgaJpZM4Wfy1m>
> .
>

2018-09-08 18:47 UTC, boydm commented
Agree. Will be Travis.

2018-09-08 18:48 UTC, ijcd commented
I meant something to quickly mimic the CI build locally. Good for
debugging. Docker++


On Sat, Sep 8, 2018 at 11:47 AM Boyd Multerer <notifications@github.com>
wrote:

> Agree. Will be Travis.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/boydm/scenic_math/pull/4#issuecomment-419664827>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAveaFwdc5XfHtUnVJUmHX47ah_pc7Uks5uZBC7gaJpZM4Wfy1m>
> .
>

2018-09-08 18:52 UTC, boydm commented
Ah. I haven't done that before. Open to suggestions.

2018-09-08 19:32 UTC, yordis commented
@boydm pretty much do what I did in the other repo.

2018-09-09 00:30 UTC, harlantwood commented
Great, flying now, will add a makefile soon.

2018-09-13 19:10 UTC, merged

2018-09-13 19:17 UTC, harlantwood commented
Oops, got caught up with work stuff and forgot about this one.  @yordis feel free to configure as you suggested in another PR if inspired.

2018-09-14 23:40 UTC, yordis commented
@harlantwood as soon as I have time I will contribute to some changes. Anyway thanks a lot!

2018-09-15 01:34 UTC, harlantwood commented
My pleasure!  Thanks for your contributions as well!